apiVersion: v1
kind: PersistentVolume
metadata:
  name: image-registry-pv
spec:
  capacity:
    storage: 100Gi 
  accessModes:
  - ReadWriteMany
  nfs: 
    path: /registryD
    server: 10.0.50.205
  persistentVolumeReclaimPolicy: Retain

