apiVersion: v1
baseDomain: example.com
compute:
- hyperthreading: Enabled
  name: worker
  replicas: 3
controlPlane:
  hyperthreading: Enabled
  name: master
  replicas: 3
metadata:
  name: ocp15
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  networkType: OpenShiftSDN
  serviceNetwork:
  - 172.30.0.0/16
platform:
  none: {}
fips: false 
pullSecret: '{"auths":{"registry.ocp15.example.com:5000": {"auth": "ZHVtbXk6ZHVtbXk=","email": "ok@gmail.com"}}}'
sshKey: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCZ6rNvb5pejaTSRoIse5KadgjNU4W9KMjWKqky3QR5btnEUR+4gCJvqvZtgoYo2DDjUj6vf5Mb root@helper.ocp15.example.com'
additionalTrustBundle: |
  -----BEGIN CERTIFICATE-----
  MIIGCzCCA/OgAwIBAgIJAM7RueTlKTYCMA0GCSqGSIb3DQEBCwUAMIGbMQswCQYD
  fiItlK1VKK9R/ChQmRDL83Dffxp1TExWsvmG5SgknXWOWdQIruGkY8vTm1LfscvA
  UOW4CuF3LbHksLUXNmB5ho15/TAh3C5+2LAkibBBySKsitrebvOrqDr+fSgY964l
  qVmsTz46HzBm0lBldzpqIwEhVH9BL6TB0L+OYCxVMqu0zdAXhJ3R6XHCNMwQ3CpC
  OHbDp2yf8dB7C38E0EoB4BUi0tLsB5WJksWkcYrhuRgvwVi1PBOBC1J1xKPhAvaQ
  r7lb3AlszDXeKonhhdpi21au0SmZyha3esUU0TglrUDF0yN6Yx3tCjVK/ceYRGr7
  lhdz63klSIhFlIv1QDmyRBGfl2wbMevyddtjhxwpXmNIjvwAHxxeKOSPihokCz3c
  n3/jitbCQolsVX6cTXut
  -----END CERTIFICATE-----
imageContentSources:
- mirrors:
  - registry.ocp15.example.com:5000/ocp15/openshift4
  source: quay.io/openshift-release-dev/ocp-release
- mirrors:
  - registry.ocp15.example.com:5000/ocp15/openshift4
  source: quay.io/openshift-release-dev/ocp-v4.0-art-dev

